export class AudRegList {

    constructor(
        public id : number ,
        public audition_id : string,
        public firstname : string,
        public emailid : string,
        public mobilenumber : string,
        public altmobilenumber : string,
        public aadhaar : string,
        public dateofbirth: Date,
        public gender : string,
        public addresstype : string,
        public addressline1 : string,
        public addressline2 : string,
        public district : string,
        public city : string,
        public pincode : string,
        public subject : string,
        public fathersname : string,
        public fathersoccupation : string,
        public fathersnumber : string,
        public mothersname : string,
        public mothersoccupation : string,
        public mothersnumber : string,
        public totalyrstrainning : string,
        public teacher1 : string,
        public sdate1: Date,
        public edate1: Date,
        public teacher2 : string,
        public sdate2: Date,
        public edate2: Date,
        public teacher3 : string,
        public sdate3: Date,
        public edate3: Date,
        public certification : string,
        public fammusic : string,
        public membername : string,
        public musicinstrument : string,
        public refperson : string,
        public aud_regn_no : string,
        public status : string) {}
  }
  export * from './AudRegList';